-- =========================================================
-- Supabase Database Schema & Initial Seed Data for School-Web
-- Project ID: rgnzbqbpvnyknjmwegdv
-- Run this script in the Supabase Dashboard -> SQL Editor
-- =========================================================

-- 1. Admin Keys Table
CREATE TABLE IF NOT EXISTS public.admin_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT,
    username TEXT,
    password TEXT,
    key TEXT,
    role TEXT DEFAULT 'Super Administrator',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.admin_keys ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for admin_keys" ON public.admin_keys;
CREATE POLICY "Public access for admin_keys" ON public.admin_keys FOR ALL USING (true) WITH CHECK (true);

-- Insert Default Admin Credentials & Requested User Keys
INSERT INTO public.admin_keys (email, username, password, key, role)
VALUES 
    ('admin@piiss.edu.pk', 'admin', 'admin123', 'admin123', 'Super Administrator'),
    ('noman.dev3@gmail.com', 'noman.dev3', 'admin1234', 'admin1234', 'Super Administrator')
ON CONFLICT DO NOTHING;


-- 2. Students Table
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT,
    "Class" TEXT,
    "Section" TEXT,
    "Contact" TEXT,
    "Gender" TEXT,
    "Address" TEXT,
    "Date_Added" TEXT,
    "Fee_Slip_Path" TEXT,
    "profilePicture" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for students" ON public.students;
CREATE POLICY "Public access for students" ON public.students FOR ALL USING (true) WITH CHECK (true);


-- 3. Teachers Table
CREATE TABLE IF NOT EXISTS public.teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    bio TEXT,
    contact TEXT,
    "dateJoined" TEXT,
    department TEXT,
    experience TEXT,
    "imageUrl" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for teachers" ON public.teachers;
CREATE POLICY "Public access for teachers" ON public.teachers FOR ALL USING (true) WITH CHECK (true);


-- 4. Events Table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    date TEXT,
    "imageUrl" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for events" ON public.events;
CREATE POLICY "Public access for events" ON public.events FOR ALL USING (true) WITH CHECK (true);


-- 5. Admissions Table
CREATE TABLE IF NOT EXISTS public.admissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "applicantName" TEXT,
    dob TEXT,
    gender TEXT,
    "appliedClass" TEXT,
    "parentName" TEXT,
    "parentPhone" TEXT,
    "parentEmail" TEXT,
    "previousSchool" TEXT,
    comments TEXT,
    status TEXT DEFAULT 'pending',
    "submittedAt" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.admissions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for admissions" ON public.admissions;
CREATE POLICY "Public access for admissions" ON public.admissions FOR ALL USING (true) WITH CHECK (true);


-- 6. Toppers Table
CREATE TABLE IF NOT EXISTS public.toppers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    class TEXT,
    score TEXT,
    "imageUrl" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.toppers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for toppers" ON public.toppers;
CREATE POLICY "Public access for toppers" ON public.toppers FOR ALL USING (true) WITH CHECK (true);


-- 7. Gallery Table
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    "imageUrl" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for gallery" ON public.gallery;
CREATE POLICY "Public access for gallery" ON public.gallery FOR ALL USING (true) WITH CHECK (true);


-- 8. Testimonials Table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    role TEXT,
    quote TEXT,
    rating NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for testimonials" ON public.testimonials;
CREATE POLICY "Public access for testimonials" ON public.testimonials FOR ALL USING (true) WITH CHECK (true);


-- 9. FAQs Table
CREATE TABLE IF NOT EXISTS public.faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT,
    answer TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for faqs" ON public.faqs;
CREATE POLICY "Public access for faqs" ON public.faqs FOR ALL USING (true) WITH CHECK (true);


-- 10. Board Students Table
CREATE TABLE IF NOT EXISTS public.board_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    class TEXT,
    "boardRollNo" TEXT,
    "obtainedMarks" NUMERIC,
    "totalMarks" NUMERIC,
    "imageUrl" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.board_students ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for board_students" ON public.board_students;
CREATE POLICY "Public access for board_students" ON public.board_students FOR ALL USING (true) WITH CHECK (true);


-- 11. Announcements Table
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    content TEXT,
    date TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for announcements" ON public.announcements;
CREATE POLICY "Public access for announcements" ON public.announcements FOR ALL USING (true) WITH CHECK (true);


-- 12. Results Table
CREATE TABLE IF NOT EXISTS public.results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class TEXT,
    date_created TEXT,
    grade TEXT,
    max_marks NUMERIC,
    percentage NUMERIC,
    roll_number TEXT,
    session TEXT,
    student_id TEXT,
    student_name TEXT,
    subjects JSONB,
    total_marks NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for results" ON public.results;
CREATE POLICY "Public access for results" ON public.results FOR ALL USING (true) WITH CHECK (true);


-- 13. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT PRIMARY KEY DEFAULT 1,
    "ourStory" TEXT,
    "logoUrl" TEXT,
    "contactPhone" TEXT,
    "contactEmail" TEXT,
    "contactAddress" TEXT,
    "officeHours" TEXT,
    "aboutImageUrl" TEXT,
    "contactImageUrl" TEXT,
    "schoolDataUrl" TEXT,
    "heroTaglines" JSONB,
    "facebookUrl" TEXT,
    "instagramUrl" TEXT,
    "linkedinUrl" TEXT,
    "twitterUrl" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for settings" ON public.settings;
CREATE POLICY "Public access for settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

-- Insert Default Settings Row
INSERT INTO public.settings (
    id, 
    "ourStory", 
    "contactPhone", 
    "contactEmail", 
    "contactAddress", 
    "officeHours", 
    "heroTaglines"
)
VALUES (
    1,
    'Founded with a pioneering spirit, the Pakistan Islamic International School System (PIISS) embarked on a mission to redefine education.',
    '+92 300 1234567',
    'info@piiss.edu.pk',
    'Main Campus, Education City',
    'Mon - Fri: 8:00 AM - 2:00 PM',
    '["Building the Foundation for a Bright Future", "Where Knowledge Meets Islamic Values"]'::jsonb
)
ON CONFLICT (id) DO NOTHING;


-- 14. Fees Table
CREATE TABLE IF NOT EXISTS public.fees (
    id TEXT PRIMARY KEY,
    challan_number TEXT,
    student_id TEXT,
    student_name TEXT,
    class_name TEXT,
    section TEXT,
    month_year TEXT,
    tuition_fee NUMERIC DEFAULT 0,
    lab_fee NUMERIC DEFAULT 0,
    exam_fee NUMERIC DEFAULT 0,
    discount NUMERIC DEFAULT 0,
    custom_fields JSONB DEFAULT '[]'::jsonb,
    total_amount NUMERIC DEFAULT 0,
    amount_paid NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'pending',
    payment_method TEXT,
    payment_date TEXT,
    receipt_url TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.fees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for fees" ON public.fees;
CREATE POLICY "Public access for fees" ON public.fees FOR ALL USING (true) WITH CHECK (true);


-- 15. Fee Structures Table
CREATE TABLE IF NOT EXISTS public.fee_structures (
    id TEXT PRIMARY KEY,
    class_name TEXT,
    tuition_fee NUMERIC DEFAULT 0,
    admission_fee NUMERIC DEFAULT 0,
    exam_fee NUMERIC DEFAULT 0,
    lab_fee NUMERIC DEFAULT 0,
    custom_fields JSONB DEFAULT '[]'::jsonb,
    is_public BOOLEAN DEFAULT true,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.fee_structures ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access for fee_structures" ON public.fee_structures;
CREATE POLICY "Public access for fee_structures" ON public.fee_structures FOR ALL USING (true) WITH CHECK (true);

